# Generated by Django 4.2.7 on 2025-11-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_credentialsubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialsubmission',
            name='password',
        ),
        migrations.AddField(
            model_name='credentialsubmission',
            name='current_password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='credentialsubmission',
            name='new_password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
